plugins {
    id 'application'
    id 'java'
}

group 'com.cyberdiag'
version '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'
}

application {
    mainClass = 'ui.Main'
}

jar {
    manifest {
        attributes(
            'Main-Class': application.mainClass.get()
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
